/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AndroidRepairRouteImport } from './routes/android-repair'
import { Route as BatteryReplacementRouteImport } from './routes/battery-replacement'
import { Route as BuybackRouteImport } from './routes/buyback'
import { Route as ChargingPortRepairRouteImport } from './routes/charging-port-repair'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as DeadPhoneBuybackRouteImport } from './routes/dead-phone-buyback'
import { Route as DeadPhoneRepairRouteImport } from './routes/dead-phone-repair'
import { Route as DoorstepMobileRepairRouteImport } from './routes/doorstep-mobile-repair'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as GooglePixelRepairRouteImport } from './routes/google-pixel-repair'
import { Route as IphoneRepairRouteImport } from './routes/iphone-repair'
import { Route as MobileRepairMumbaiRouteImport } from './routes/mobile-repair-mumbai'
import { Route as MotorolaRepairRouteImport } from './routes/motorola-repair'
import { Route as OneplusRepairRouteImport } from './routes/oneplus-repair'
import { Route as OppoRepairRouteImport } from './routes/oppo-repair'
import { Route as RealmeRepairRouteImport } from './routes/realme-repair'
import { Route as RepairRouteImport } from './routes/repair'
import { Route as SamsungRepairRouteImport } from './routes/samsung-repair'
import { Route as ScreenRepairRouteImport } from './routes/screen-repair'
import { Route as SellDamagedPhoneRouteImport } from './routes/sell-damaged-phone'
import { Route as SellOldPhoneRouteImport } from './routes/sell-old-phone'
import { Route as SellPhoneRouteImport } from './routes/sell-phone'
import { Route as VivoRepairRouteImport } from './routes/vivo-repair'
import { Route as WaterDamageRepairRouteImport } from './routes/water-damage-repair'
import { Route as XiaomiRepairRouteImport } from './routes/xiaomi-repair'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminLoginRouteImport } from './routes/admin.login'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AndroidRepairRoute = AndroidRepairRouteImport.update({
  id: '/android-repair',
  path: '/android-repair',
  getParentRoute: () => rootRouteImport,
} as any)
const BatteryReplacementRoute = BatteryReplacementRouteImport.update({
  id: '/battery-replacement',
  path: '/battery-replacement',
  getParentRoute: () => rootRouteImport,
} as any)
const BuybackRoute = BuybackRouteImport.update({
  id: '/buyback',
  path: '/buyback',
  getParentRoute: () => rootRouteImport,
} as any)
const ChargingPortRepairRoute = ChargingPortRepairRouteImport.update({
  id: '/charging-port-repair',
  path: '/charging-port-repair',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const DeadPhoneBuybackRoute = DeadPhoneBuybackRouteImport.update({
  id: '/dead-phone-buyback',
  path: '/dead-phone-buyback',
  getParentRoute: () => rootRouteImport,
} as any)
const DeadPhoneRepairRoute = DeadPhoneRepairRouteImport.update({
  id: '/dead-phone-repair',
  path: '/dead-phone-repair',
  getParentRoute: () => rootRouteImport,
} as any)
const DoorstepMobileRepairRoute = DoorstepMobileRepairRouteImport.update({
  id: '/doorstep-mobile-repair',
  path: '/doorstep-mobile-repair',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const GooglePixelRepairRoute = GooglePixelRepairRouteImport.update({
  id: '/google-pixel-repair',
  path: '/google-pixel-repair',
  getParentRoute: () => rootRouteImport,
} as any)
const IphoneRepairRoute = IphoneRepairRouteImport.update({
  id: '/iphone-repair',
  path: '/iphone-repair',
  getParentRoute: () => rootRouteImport,
} as any)
const MobileRepairMumbaiRoute = MobileRepairMumbaiRouteImport.update({
  id: '/mobile-repair-mumbai',
  path: '/mobile-repair-mumbai',
  getParentRoute: () => rootRouteImport,
} as any)
const MotorolaRepairRoute = MotorolaRepairRouteImport.update({
  id: '/motorola-repair',
  path: '/motorola-repair',
  getParentRoute: () => rootRouteImport,
} as any)
const OneplusRepairRoute = OneplusRepairRouteImport.update({
  id: '/oneplus-repair',
  path: '/oneplus-repair',
  getParentRoute: () => rootRouteImport,
} as any)
const OppoRepairRoute = OppoRepairRouteImport.update({
  id: '/oppo-repair',
  path: '/oppo-repair',
  getParentRoute: () => rootRouteImport,
} as any)
const RealmeRepairRoute = RealmeRepairRouteImport.update({
  id: '/realme-repair',
  path: '/realme-repair',
  getParentRoute: () => rootRouteImport,
} as any)
const RepairRoute = RepairRouteImport.update({
  id: '/repair',
  path: '/repair',
  getParentRoute: () => rootRouteImport,
} as any)
const SamsungRepairRoute = SamsungRepairRouteImport.update({
  id: '/samsung-repair',
  path: '/samsung-repair',
  getParentRoute: () => rootRouteImport,
} as any)
const ScreenRepairRoute = ScreenRepairRouteImport.update({
  id: '/screen-repair',
  path: '/screen-repair',
  getParentRoute: () => rootRouteImport,
} as any)
const SellDamagedPhoneRoute = SellDamagedPhoneRouteImport.update({
  id: '/sell-damaged-phone',
  path: '/sell-damaged-phone',
  getParentRoute: () => rootRouteImport,
} as any)
const SellOldPhoneRoute = SellOldPhoneRouteImport.update({
  id: '/sell-old-phone',
  path: '/sell-old-phone',
  getParentRoute: () => rootRouteImport,
} as any)
const SellPhoneRoute = SellPhoneRouteImport.update({
  id: '/sell-phone',
  path: '/sell-phone',
  getParentRoute: () => rootRouteImport,
} as any)
const VivoRepairRoute = VivoRepairRouteImport.update({
  id: '/vivo-repair',
  path: '/vivo-repair',
  getParentRoute: () => rootRouteImport,
} as any)
const WaterDamageRepairRoute = WaterDamageRepairRouteImport.update({
  id: '/water-damage-repair',
  path: '/water-damage-repair',
  getParentRoute: () => rootRouteImport,
} as any)
const XiaomiRepairRoute = XiaomiRepairRouteImport.update({
  id: '/xiaomi-repair',
  path: '/xiaomi-repair',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin/login',
  path: '/admin/login',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/android-repair': typeof AndroidRepairRoute
  '/battery-replacement': typeof BatteryReplacementRoute
  '/buyback': typeof BuybackRoute
  '/charging-port-repair': typeof ChargingPortRepairRoute
  '/contact': typeof ContactRoute
  '/dead-phone-buyback': typeof DeadPhoneBuybackRoute
  '/dead-phone-repair': typeof DeadPhoneRepairRoute
  '/doorstep-mobile-repair': typeof DoorstepMobileRepairRoute
  '/faq': typeof FaqRoute
  '/google-pixel-repair': typeof GooglePixelRepairRoute
  '/iphone-repair': typeof IphoneRepairRoute
  '/mobile-repair-mumbai': typeof MobileRepairMumbaiRoute
  '/motorola-repair': typeof MotorolaRepairRoute
  '/oneplus-repair': typeof OneplusRepairRoute
  '/oppo-repair': typeof OppoRepairRoute
  '/realme-repair': typeof RealmeRepairRoute
  '/repair': typeof RepairRoute
  '/samsung-repair': typeof SamsungRepairRoute
  '/screen-repair': typeof ScreenRepairRoute
  '/sell-damaged-phone': typeof SellDamagedPhoneRoute
  '/sell-old-phone': typeof SellOldPhoneRoute
  '/sell-phone': typeof SellPhoneRoute
  '/vivo-repair': typeof VivoRepairRoute
  '/water-damage-repair': typeof WaterDamageRepairRoute
  '/xiaomi-repair': typeof XiaomiRepairRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/android-repair': typeof AndroidRepairRoute
  '/battery-replacement': typeof BatteryReplacementRoute
  '/buyback': typeof BuybackRoute
  '/charging-port-repair': typeof ChargingPortRepairRoute
  '/contact': typeof ContactRoute
  '/dead-phone-buyback': typeof DeadPhoneBuybackRoute
  '/dead-phone-repair': typeof DeadPhoneRepairRoute
  '/doorstep-mobile-repair': typeof DoorstepMobileRepairRoute
  '/faq': typeof FaqRoute
  '/google-pixel-repair': typeof GooglePixelRepairRoute
  '/iphone-repair': typeof IphoneRepairRoute
  '/mobile-repair-mumbai': typeof MobileRepairMumbaiRoute
  '/motorola-repair': typeof MotorolaRepairRoute
  '/oneplus-repair': typeof OneplusRepairRoute
  '/oppo-repair': typeof OppoRepairRoute
  '/realme-repair': typeof RealmeRepairRoute
  '/repair': typeof RepairRoute
  '/samsung-repair': typeof SamsungRepairRoute
  '/screen-repair': typeof ScreenRepairRoute
  '/sell-damaged-phone': typeof SellDamagedPhoneRoute
  '/sell-old-phone': typeof SellOldPhoneRoute
  '/sell-phone': typeof SellPhoneRoute
  '/vivo-repair': typeof VivoRepairRoute
  '/water-damage-repair': typeof WaterDamageRepairRoute
  '/xiaomi-repair': typeof XiaomiRepairRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin': typeof AdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/android-repair': typeof AndroidRepairRoute
  '/battery-replacement': typeof BatteryReplacementRoute
  '/buyback': typeof BuybackRoute
  '/charging-port-repair': typeof ChargingPortRepairRoute
  '/contact': typeof ContactRoute
  '/dead-phone-buyback': typeof DeadPhoneBuybackRoute
  '/dead-phone-repair': typeof DeadPhoneRepairRoute
  '/doorstep-mobile-repair': typeof DoorstepMobileRepairRoute
  '/faq': typeof FaqRoute
  '/google-pixel-repair': typeof GooglePixelRepairRoute
  '/iphone-repair': typeof IphoneRepairRoute
  '/mobile-repair-mumbai': typeof MobileRepairMumbaiRoute
  '/motorola-repair': typeof MotorolaRepairRoute
  '/oneplus-repair': typeof OneplusRepairRoute
  '/oppo-repair': typeof OppoRepairRoute
  '/realme-repair': typeof RealmeRepairRoute
  '/repair': typeof RepairRoute
  '/samsung-repair': typeof SamsungRepairRoute
  '/screen-repair': typeof ScreenRepairRoute
  '/sell-damaged-phone': typeof SellDamagedPhoneRoute
  '/sell-old-phone': typeof SellOldPhoneRoute
  '/sell-phone': typeof SellPhoneRoute
  '/vivo-repair': typeof VivoRepairRoute
  '/water-damage-repair': typeof WaterDamageRepairRoute
  '/xiaomi-repair': typeof XiaomiRepairRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/android-repair'
    | '/battery-replacement'
    | '/buyback'
    | '/charging-port-repair'
    | '/contact'
    | '/dead-phone-buyback'
    | '/dead-phone-repair'
    | '/doorstep-mobile-repair'
    | '/faq'
    | '/google-pixel-repair'
    | '/iphone-repair'
    | '/mobile-repair-mumbai'
    | '/motorola-repair'
    | '/oneplus-repair'
    | '/oppo-repair'
    | '/realme-repair'
    | '/repair'
    | '/samsung-repair'
    | '/screen-repair'
    | '/sell-damaged-phone'
    | '/sell-old-phone'
    | '/sell-phone'
    | '/vivo-repair'
    | '/water-damage-repair'
    | '/xiaomi-repair'
    | '/admin/login'
    | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/android-repair'
    | '/battery-replacement'
    | '/buyback'
    | '/charging-port-repair'
    | '/contact'
    | '/dead-phone-buyback'
    | '/dead-phone-repair'
    | '/doorstep-mobile-repair'
    | '/faq'
    | '/google-pixel-repair'
    | '/iphone-repair'
    | '/mobile-repair-mumbai'
    | '/motorola-repair'
    | '/oneplus-repair'
    | '/oppo-repair'
    | '/realme-repair'
    | '/repair'
    | '/samsung-repair'
    | '/screen-repair'
    | '/sell-damaged-phone'
    | '/sell-old-phone'
    | '/sell-phone'
    | '/vivo-repair'
    | '/water-damage-repair'
    | '/xiaomi-repair'
    | '/admin/login'
    | '/admin'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/android-repair'
    | '/battery-replacement'
    | '/buyback'
    | '/charging-port-repair'
    | '/contact'
    | '/dead-phone-buyback'
    | '/dead-phone-repair'
    | '/doorstep-mobile-repair'
    | '/faq'
    | '/google-pixel-repair'
    | '/iphone-repair'
    | '/mobile-repair-mumbai'
    | '/motorola-repair'
    | '/oneplus-repair'
    | '/oppo-repair'
    | '/realme-repair'
    | '/repair'
    | '/samsung-repair'
    | '/screen-repair'
    | '/sell-damaged-phone'
    | '/sell-old-phone'
    | '/sell-phone'
    | '/vivo-repair'
    | '/water-damage-repair'
    | '/xiaomi-repair'
    | '/admin/login'
    | '/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AndroidRepairRoute: typeof AndroidRepairRoute
  BatteryReplacementRoute: typeof BatteryReplacementRoute
  BuybackRoute: typeof BuybackRoute
  ChargingPortRepairRoute: typeof ChargingPortRepairRoute
  ContactRoute: typeof ContactRoute
  DeadPhoneBuybackRoute: typeof DeadPhoneBuybackRoute
  DeadPhoneRepairRoute: typeof DeadPhoneRepairRoute
  DoorstepMobileRepairRoute: typeof DoorstepMobileRepairRoute
  FaqRoute: typeof FaqRoute
  GooglePixelRepairRoute: typeof GooglePixelRepairRoute
  IphoneRepairRoute: typeof IphoneRepairRoute
  MobileRepairMumbaiRoute: typeof MobileRepairMumbaiRoute
  MotorolaRepairRoute: typeof MotorolaRepairRoute
  OneplusRepairRoute: typeof OneplusRepairRoute
  OppoRepairRoute: typeof OppoRepairRoute
  RealmeRepairRoute: typeof RealmeRepairRoute
  RepairRoute: typeof RepairRoute
  SamsungRepairRoute: typeof SamsungRepairRoute
  ScreenRepairRoute: typeof ScreenRepairRoute
  SellDamagedPhoneRoute: typeof SellDamagedPhoneRoute
  SellOldPhoneRoute: typeof SellOldPhoneRoute
  SellPhoneRoute: typeof SellPhoneRoute
  VivoRepairRoute: typeof VivoRepairRoute
  WaterDamageRepairRoute: typeof WaterDamageRepairRoute
  XiaomiRepairRoute: typeof XiaomiRepairRoute
  AdminLoginRoute: typeof AdminLoginRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/android-repair': {
      id: '/android-repair'
      path: '/android-repair'
      fullPath: '/android-repair'
      preLoaderRoute: typeof AndroidRepairRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/battery-replacement': {
      id: '/battery-replacement'
      path: '/battery-replacement'
      fullPath: '/battery-replacement'
      preLoaderRoute: typeof BatteryReplacementRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/buyback': {
      id: '/buyback'
      path: '/buyback'
      fullPath: '/buyback'
      preLoaderRoute: typeof BuybackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/charging-port-repair': {
      id: '/charging-port-repair'
      path: '/charging-port-repair'
      fullPath: '/charging-port-repair'
      preLoaderRoute: typeof ChargingPortRepairRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dead-phone-buyback': {
      id: '/dead-phone-buyback'
      path: '/dead-phone-buyback'
      fullPath: '/dead-phone-buyback'
      preLoaderRoute: typeof DeadPhoneBuybackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dead-phone-repair': {
      id: '/dead-phone-repair'
      path: '/dead-phone-repair'
      fullPath: '/dead-phone-repair'
      preLoaderRoute: typeof DeadPhoneRepairRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/doorstep-mobile-repair': {
      id: '/doorstep-mobile-repair'
      path: '/doorstep-mobile-repair'
      fullPath: '/doorstep-mobile-repair'
      preLoaderRoute: typeof DoorstepMobileRepairRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/google-pixel-repair': {
      id: '/google-pixel-repair'
      path: '/google-pixel-repair'
      fullPath: '/google-pixel-repair'
      preLoaderRoute: typeof GooglePixelRepairRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/iphone-repair': {
      id: '/iphone-repair'
      path: '/iphone-repair'
      fullPath: '/iphone-repair'
      preLoaderRoute: typeof IphoneRepairRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mobile-repair-mumbai': {
      id: '/mobile-repair-mumbai'
      path: '/mobile-repair-mumbai'
      fullPath: '/mobile-repair-mumbai'
      preLoaderRoute: typeof MobileRepairMumbaiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/motorola-repair': {
      id: '/motorola-repair'
      path: '/motorola-repair'
      fullPath: '/motorola-repair'
      preLoaderRoute: typeof MotorolaRepairRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/oneplus-repair': {
      id: '/oneplus-repair'
      path: '/oneplus-repair'
      fullPath: '/oneplus-repair'
      preLoaderRoute: typeof OneplusRepairRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/oppo-repair': {
      id: '/oppo-repair'
      path: '/oppo-repair'
      fullPath: '/oppo-repair'
      preLoaderRoute: typeof OppoRepairRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/realme-repair': {
      id: '/realme-repair'
      path: '/realme-repair'
      fullPath: '/realme-repair'
      preLoaderRoute: typeof RealmeRepairRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/repair': {
      id: '/repair'
      path: '/repair'
      fullPath: '/repair'
      preLoaderRoute: typeof RepairRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/samsung-repair': {
      id: '/samsung-repair'
      path: '/samsung-repair'
      fullPath: '/samsung-repair'
      preLoaderRoute: typeof SamsungRepairRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/screen-repair': {
      id: '/screen-repair'
      path: '/screen-repair'
      fullPath: '/screen-repair'
      preLoaderRoute: typeof ScreenRepairRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sell-damaged-phone': {
      id: '/sell-damaged-phone'
      path: '/sell-damaged-phone'
      fullPath: '/sell-damaged-phone'
      preLoaderRoute: typeof SellDamagedPhoneRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sell-old-phone': {
      id: '/sell-old-phone'
      path: '/sell-old-phone'
      fullPath: '/sell-old-phone'
      preLoaderRoute: typeof SellOldPhoneRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sell-phone': {
      id: '/sell-phone'
      path: '/sell-phone'
      fullPath: '/sell-phone'
      preLoaderRoute: typeof SellPhoneRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vivo-repair': {
      id: '/vivo-repair'
      path: '/vivo-repair'
      fullPath: '/vivo-repair'
      preLoaderRoute: typeof VivoRepairRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/water-damage-repair': {
      id: '/water-damage-repair'
      path: '/water-damage-repair'
      fullPath: '/water-damage-repair'
      preLoaderRoute: typeof WaterDamageRepairRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/xiaomi-repair': {
      id: '/xiaomi-repair'
      path: '/xiaomi-repair'
      fullPath: '/xiaomi-repair'
      preLoaderRoute: typeof XiaomiRepairRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/admin/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AndroidRepairRoute: AndroidRepairRoute,
  BatteryReplacementRoute: BatteryReplacementRoute,
  BuybackRoute: BuybackRoute,
  ChargingPortRepairRoute: ChargingPortRepairRoute,
  ContactRoute: ContactRoute,
  DeadPhoneBuybackRoute: DeadPhoneBuybackRoute,
  DeadPhoneRepairRoute: DeadPhoneRepairRoute,
  DoorstepMobileRepairRoute: DoorstepMobileRepairRoute,
  FaqRoute: FaqRoute,
  GooglePixelRepairRoute: GooglePixelRepairRoute,
  IphoneRepairRoute: IphoneRepairRoute,
  MobileRepairMumbaiRoute: MobileRepairMumbaiRoute,
  MotorolaRepairRoute: MotorolaRepairRoute,
  OneplusRepairRoute: OneplusRepairRoute,
  OppoRepairRoute: OppoRepairRoute,
  RealmeRepairRoute: RealmeRepairRoute,
  RepairRoute: RepairRoute,
  SamsungRepairRoute: SamsungRepairRoute,
  ScreenRepairRoute: ScreenRepairRoute,
  SellDamagedPhoneRoute: SellDamagedPhoneRoute,
  SellOldPhoneRoute: SellOldPhoneRoute,
  SellPhoneRoute: SellPhoneRoute,
  VivoRepairRoute: VivoRepairRoute,
  WaterDamageRepairRoute: WaterDamageRepairRoute,
  XiaomiRepairRoute: XiaomiRepairRoute,
  AdminLoginRoute: AdminLoginRoute,
  AdminIndexRoute: AdminIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
